// Generated by dts-bundle v0.7.3

declare module 'ngx-emoji' {
    export { NgxEmojiModule } from 'ngx-emoji/ngx-emoji.module';
    export { PrettyInputComponent } from 'ngx-emoji/pretty-input.component';
    export { PrettyTextComponent } from 'ngx-emoji/pretty-text.component';
}

declare module 'ngx-emoji/ngx-emoji.module' {
    export class NgxEmojiModule {
    }
}

declare module 'ngx-emoji/pretty-input.component' {
    export class PrettyInputComponent {
    }
}

declare module 'ngx-emoji/pretty-text.component' {
    export class PrettyTextComponent {
    }
}

